<?xml version='1.0' encoding='UTF-8'?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:plink="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:wsdlsoap11="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdlsoap12="http://schemas.xmlsoap.org/wsdl/soap12/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap11enc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:soap11env="http://schemas.xmlsoap.org/soap/envelope/" xmlns:soap12env="http://www.w3.org/2003/05/soap-envelope" xmlns:soap12enc="http://www.w3.org/2003/05/soap-encoding" xmlns:wsa="http://schemas.xmlsoap.org/ws/2003/03/addressing" xmlns:xop="http://www.w3.org/2004/08/xop/include" xmlns:http="http://schemas.xmlsoap.org/wsdl/http/" xmlns:tns="jiujitsu.escola.services" targetNamespace="jiujitsu.escola.services" elementFormDefault="qualified">
  <xs:complexType name="MatriculaModel">
    <xs:sequence>
      <xs:element name="id" type="xs:integer" minOccurs="0" nillable="true"/>
      <xs:element name="nome_aluno" type="xs:string" minOccurs="0" nillable="true"/>
      <xs:element name="cpf" type="xs:string" minOccurs="0" nillable="true"/>
      <xs:element name="id_curso" type="xs:integer" minOccurs="0" nillable="true"/>
      <xs:element name="plano" type="xs:string" minOccurs="0" nillable="true"/>
      <xs:element name="status" type="xs:string" minOccurs="0" nillable="true"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="listar_matriculas_ativas"/>
  <xs:complexType name="CursoModel">
    <xs:sequence>
      <xs:element name="id" type="xs:integer" minOccurs="0" nillable="true"/>
      <xs:element name="nome" type="xs:string" minOccurs="0" nillable="true"/>
      <xs:element name="categoria" type="xs:string" minOccurs="0" nillable="true"/>
      <xs:element name="valor" type="xs:string" minOccurs="0" nillable="true"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="MatriculaModelArray">
    <xs:sequence>
      <xs:element name="MatriculaModel" type="tns:MatriculaModel" minOccurs="0" maxOccurs="unbounded" nillable="true"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="atualizar_status_matricula">
    <xs:sequence>
      <xs:element name="id_matricula" type="xs:integer" minOccurs="0" nillable="true"/>
      <xs:element name="status" type="xs:string" minOccurs="0" nillable="true"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="atualizar_status_matriculaResponse">
    <xs:sequence>
      <xs:element name="atualizar_status_matriculaResult" type="xs:boolean" minOccurs="0" nillable="true"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="consultar_cursos">
    <xs:sequence>
      <xs:element name="categoria" type="xs:string" minOccurs="0" nillable="true"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="consultar_matricula">
    <xs:sequence>
      <xs:element name="id_matricula" type="xs:integer" minOccurs="0" nillable="true"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="deletar_matricula">
    <xs:sequence>
      <xs:element name="id_matricula" type="xs:integer" minOccurs="0" nillable="true"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="deletar_matriculaResponse">
    <xs:sequence>
      <xs:element name="deletar_matriculaResult" type="xs:boolean" minOccurs="0" nillable="true"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="registrar_matricula">
    <xs:sequence>
      <xs:element name="nome_aluno" type="xs:string" minOccurs="0" nillable="true"/>
      <xs:element name="cpf" type="xs:string" minOccurs="0" nillable="true"/>
      <xs:element name="id_curso" type="xs:integer" minOccurs="0" nillable="true"/>
      <xs:element name="plano" type="xs:string" minOccurs="0" nillable="true"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="registrar_matriculaResponse">
    <xs:sequence>
      <xs:element name="registrar_matriculaResult" type="xs:integer" minOccurs="0" nillable="true"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="CursoModelArray">
    <xs:sequence>
      <xs:element name="CursoModel" type="tns:CursoModel" minOccurs="0" maxOccurs="unbounded" nillable="true"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="consultar_matriculaResponse">
    <xs:sequence>
      <xs:element name="consultar_matriculaResult" type="tns:MatriculaModel" minOccurs="0" nillable="true"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="listar_matriculas_ativasResponse">
    <xs:sequence>
      <xs:element name="listar_matriculas_ativasResult" type="tns:MatriculaModelArray" minOccurs="0" nillable="true"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="consultar_cursosResponse">
    <xs:sequence>
      <xs:element name="consultar_cursosResult" type="tns:CursoModelArray" minOccurs="0" nillable="true"/>
    </xs:sequence>
  </xs:complexType>
  <xs:element name="MatriculaModel" type="tns:MatriculaModel"/>
  <xs:element name="listar_matriculas_ativas" type="tns:listar_matriculas_ativas"/>
  <xs:element name="CursoModel" type="tns:CursoModel"/>
  <xs:element name="MatriculaModelArray" type="tns:MatriculaModelArray"/>
  <xs:element name="atualizar_status_matricula" type="tns:atualizar_status_matricula"/>
  <xs:element name="atualizar_status_matriculaResponse" type="tns:atualizar_status_matriculaResponse"/>
  <xs:element name="consultar_cursos" type="tns:consultar_cursos"/>
  <xs:element name="consultar_matricula" type="tns:consultar_matricula"/>
  <xs:element name="deletar_matricula" type="tns:deletar_matricula"/>
  <xs:element name="deletar_matriculaResponse" type="tns:deletar_matriculaResponse"/>
  <xs:element name="registrar_matricula" type="tns:registrar_matricula"/>
  <xs:element name="registrar_matriculaResponse" type="tns:registrar_matriculaResponse"/>
  <xs:element name="CursoModelArray" type="tns:CursoModelArray"/>
  <xs:element name="consultar_matriculaResponse" type="tns:consultar_matriculaResponse"/>
  <xs:element name="listar_matriculas_ativasResponse" type="tns:listar_matriculas_ativasResponse"/>
  <xs:element name="consultar_cursosResponse" type="tns:consultar_cursosResponse"/>
</xs:schema>
